# Generated by Django 4.1.2 on 2022-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_statuses_created_at_alter_statuses_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type', to='webapp.types'),
        ),
    ]
