# Generated by Django 4.1.2 on 2022-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_tasks_type_tasks_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.ManyToManyField(related_name='type', to='webapp.types'),
        ),
    ]
