# Generated by Django 4.1.2 on 2022-10-11 10:36

from django.db import migrations, models
import webapp.models.tasks


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_tasks_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.models.tasks.CustomLengthValidator(30), webapp.models.tasks.validate_digits_letters], verbose_name='Summary'),
        ),
    ]
