# Generated by Django 4.1.2 on 2022-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_projects_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Delete time'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
