# Generated by Django 4.1.2 on 2022-10-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tasks_deleted_at_tasks_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Delete time'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.projects', verbose_name='Project'),
        ),
    ]
