# Generated by Django 4.1.2 on 2022-10-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_projects_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='projects',
            name='is_deleted_user',
            field=models.BooleanField(default=False, verbose_name='Deleted user'),
        ),
    ]
