# Generated by Django 4.1.2 on 2022-10-25 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_rename_users_projects_user_projects_is_deleted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
